// cropMeta.ts
// Icon + display label per crop, shared so screens don't quietly drift apart
// the way the chip/pill styles did before ui.tsx existed.

import { CropKey } from './engines/scheduleEngine';
import { colors } from './theme';

export const CROP_META: Record<CropKey, { label: string; icon: string }> = {
  tomatoes: { label: 'Tomatoes', icon: '🍅' },
  cucumbers: { label: 'Cucumbers', icon: '🥒' },
  lettuce: { label: 'Lettuce', icon: '🥬' },
  carrots: { label: 'Carrots', icon: '🥕' },
  peppers: { label: 'Peppers', icon: '🫑' },
  basil: { label: 'Basil', icon: '🌿' },
  potatoes: { label: 'Potatoes', icon: '🥔' },
  garlic: { label: 'Garlic', icon: '🧄' },
  strawberries: { label: 'Strawberries', icon: '🍓' },
  squash: { label: 'Squash', icon: '🎃' },
  corn: { label: 'Corn', icon: '🌽' },
  onions: { label: 'Onions', icon: '🧅' },
  broccoli: { label: 'Broccoli', icon: '🥦' },
  cauliflower: { label: 'Cauliflower', icon: '🥦' },
  cabbage: { label: 'Cabbage', icon: '🥬' },
  kale: { label: 'Kale', icon: '🥬' },
  spinach: { label: 'Spinach', icon: '🥬' },
  chard: { label: 'Swiss chard', icon: '🥬' },
  beets: { label: 'Beets', icon: '🟣' },
  radishes: { label: 'Radishes', icon: '🔴' },
  turnips: { label: 'Turnips', icon: '⚪' },
  rutabaga: { label: 'Rutabaga', icon: '🟤' },
  kohlrabi: { label: 'Kohlrabi', icon: '🟢' },
  peas: { label: 'Peas', icon: '🫛' },
  beans: { label: 'Green beans', icon: '🫘' },
  zucchini: { label: 'Zucchini', icon: '🥒' },
  pumpkin: { label: 'Pumpkin', icon: '🟠' },
  eggplant: { label: 'Eggplant', icon: '🍆' },
  okra: { label: 'Okra', icon: '🌿' },
  watermelon: { label: 'Watermelon', icon: '🍉' },
  cantaloupe: { label: 'Cantaloupe', icon: '🍈' },
  leeks: { label: 'Leeks', icon: '🧅' },
  sweetpotatoes: { label: 'Sweet potatoes', icon: '🍠' },
  celery: { label: 'Celery', icon: '🌿' },
  asparagus: { label: 'Asparagus', icon: '🌱' },
  brusselssprouts: { label: 'Brussels sprouts', icon: '🥬' },
  arugula: { label: 'Arugula', icon: '🥬' },
  collards: { label: 'Collard greens', icon: '🥬' },
  bokchoy: { label: 'Bok choy', icon: '🥬' },
  cilantro: { label: 'Cilantro', icon: '🌿' },
  parsley: { label: 'Parsley', icon: '🌿' },
  mint: { label: 'Mint', icon: '🌿' },
  rosemary: { label: 'Rosemary', icon: '🌿' },
  thyme: { label: 'Thyme', icon: '🌿' },
  oregano: { label: 'Oregano', icon: '🌿' },
  dill: { label: 'Dill', icon: '🌿' },
  chives: { label: 'Chives', icon: '🌿' },
  sage: { label: 'Sage', icon: '🌿' },
  blueberries: { label: 'Blueberries', icon: '🫐' },
  raspberries: { label: 'Raspberries', icon: '🍒' },
  blackberries: { label: 'Blackberries', icon: '🌱' },
  grapes: { label: 'Grapes', icon: '🍇' },
  rhubarb: { label: 'Rhubarb', icon: '🌱' },
  figs: { label: 'Figs', icon: '🌱' },
  marigold: { label: 'Marigold', icon: '🌱' },
  zinnia: { label: 'Zinnia', icon: '🌱' },
  sunflower: { label: 'Sunflower', icon: '🌻' },
  cosmos: { label: 'Cosmos', icon: '🌱' },
  nasturtium: { label: 'Nasturtium', icon: '🌱' },
  pansy: { label: 'Pansy', icon: '🌱' },
  other: { label: 'Something else', icon: '🌱' },
};

export type CropCategory = 'vegetable' | 'fruit' | 'flower';

export const CROP_CATEGORY: Record<CropKey, CropCategory> = {
  tomatoes: 'vegetable',
  cucumbers: 'vegetable',
  lettuce: 'vegetable',
  carrots: 'vegetable',
  peppers: 'vegetable',
  basil: 'vegetable',
  potatoes: 'vegetable',
  garlic: 'vegetable',
  strawberries: 'fruit',
  squash: 'vegetable',
  corn: 'vegetable',
  onions: 'vegetable',
  broccoli: 'vegetable',
  cauliflower: 'vegetable',
  cabbage: 'vegetable',
  kale: 'vegetable',
  spinach: 'vegetable',
  chard: 'vegetable',
  beets: 'vegetable',
  radishes: 'vegetable',
  turnips: 'vegetable',
  rutabaga: 'vegetable',
  kohlrabi: 'vegetable',
  peas: 'vegetable',
  beans: 'vegetable',
  zucchini: 'vegetable',
  pumpkin: 'vegetable',
  eggplant: 'vegetable',
  okra: 'vegetable',
  watermelon: 'fruit',
  cantaloupe: 'fruit',
  leeks: 'vegetable',
  sweetpotatoes: 'vegetable',
  celery: 'vegetable',
  asparagus: 'vegetable',
  brusselssprouts: 'vegetable',
  arugula: 'vegetable',
  collards: 'vegetable',
  bokchoy: 'vegetable',
  cilantro: 'vegetable',
  parsley: 'vegetable',
  mint: 'vegetable',
  rosemary: 'vegetable',
  thyme: 'vegetable',
  oregano: 'vegetable',
  dill: 'vegetable',
  chives: 'vegetable',
  sage: 'vegetable',
  blueberries: 'fruit',
  raspberries: 'fruit',
  blackberries: 'fruit',
  grapes: 'fruit',
  rhubarb: 'fruit',
  figs: 'fruit',
  marigold: 'flower',
  zinnia: 'flower',
  sunflower: 'flower',
  cosmos: 'flower',
  nasturtium: 'flower',
  pansy: 'flower',
  other: 'vegetable',
};

// Icon-chip background per crop — used anywhere a crop gets a small round
// swatch (My Garden cards, Log entries). Cycles through the same four
// pastel swatches the free crops use; there's no dedicated color per crop.
const CROP_ICON_BG: Record<CropKey, string> = {
  tomatoes: colors.selectedBg,
  cucumbers: colors.sevFyiBg,
  lettuce: colors.sevLowBg,
  carrots: colors.sevSoonBg,
  peppers: colors.selectedBg,
  basil: colors.sevLowBg,
  potatoes: colors.sevFyiBg,
  garlic: colors.sevSoonBg,
  strawberries: colors.selectedBg,
  squash: colors.sevFyiBg,
  corn: colors.sevSoonBg,
  onions: colors.sevLowBg,
  broccoli: colors.sevLowBg,
  cauliflower: colors.sevFyiBg,
  cabbage: colors.sevSoonBg,
  kale: colors.selectedBg,
  spinach: colors.sevLowBg,
  chard: colors.sevFyiBg,
  beets: colors.sevSoonBg,
  radishes: colors.selectedBg,
  turnips: colors.sevLowBg,
  rutabaga: colors.sevFyiBg,
  kohlrabi: colors.sevSoonBg,
  peas: colors.selectedBg,
  beans: colors.sevLowBg,
  zucchini: colors.sevFyiBg,
  pumpkin: colors.sevSoonBg,
  eggplant: colors.selectedBg,
  okra: colors.sevLowBg,
  watermelon: colors.sevFyiBg,
  cantaloupe: colors.sevSoonBg,
  leeks: colors.selectedBg,
  sweetpotatoes: colors.sevLowBg,
  celery: colors.sevFyiBg,
  asparagus: colors.sevSoonBg,
  brusselssprouts: colors.selectedBg,
  arugula: colors.sevLowBg,
  collards: colors.sevFyiBg,
  bokchoy: colors.sevSoonBg,
  cilantro: colors.selectedBg,
  parsley: colors.sevLowBg,
  mint: colors.sevFyiBg,
  rosemary: colors.sevSoonBg,
  thyme: colors.selectedBg,
  oregano: colors.sevLowBg,
  dill: colors.sevFyiBg,
  chives: colors.sevSoonBg,
  sage: colors.selectedBg,
  blueberries: colors.sevLowBg,
  raspberries: colors.sevFyiBg,
  blackberries: colors.sevSoonBg,
  grapes: colors.selectedBg,
  rhubarb: colors.sevLowBg,
  figs: colors.sevFyiBg,
  marigold: colors.sevSoonBg,
  zinnia: colors.selectedBg,
  sunflower: colors.sevLowBg,
  cosmos: colors.sevFyiBg,
  nasturtium: colors.sevSoonBg,
  pansy: colors.selectedBg,
  other: colors.selectedBg,
};

// Crops with no real, dedicated emoji fall back to a plain colored dot
// (🔴🟣⚪️...), which reads as "no icon" rather than as that vegetable, and
// several land on the same dot. These get a two-letter colored monogram
// badge instead (see components/ui.tsx's CropIcon), colored to evoke the
// actual vegetable (radish red, beet magenta, rutabaga's golden flesh...).
// Crops that already share a real but generic emoji (basil/mint/etc. all
// using 🌿) are left alone — that's a legible, still-relevant icon, just
// not unique, which is a smaller problem than having no real icon at all.
export const CROP_BADGE: Partial<Record<CropKey, { letters: string; color: string }>> = {
  beets: { letters: 'BT', color: '#8E3A56' },
  radishes: { letters: 'RD', color: '#C1503F' },
  turnips: { letters: 'TN', color: '#9C8AA8' },
  rutabaga: { letters: 'RT', color: '#C08A3E' },
  kohlrabi: { letters: 'KB', color: '#8FA83E' },
  pumpkin: { letters: 'PM', color: '#D9822F' },
  blackberries: { letters: 'BK', color: '#4A3352' },
  rhubarb: { letters: 'RB', color: '#C15C6B' },
  figs: { letters: 'FG', color: '#6B4A4E' },
  marigold: { letters: 'MG', color: '#C98A1F' },
  zinnia: { letters: 'ZN', color: '#B84568' },
  cosmos: { letters: 'CS', color: '#C97F92' },
  nasturtium: { letters: 'NT', color: '#D1652E' },
  pansy: { letters: 'PN', color: '#6B4C8A' },
};

export function cropLabel(crop: CropKey | string): string {
  return CROP_META[crop as CropKey]?.label ?? crop.charAt(0).toUpperCase() + crop.slice(1);
}

export function cropIcon(crop: CropKey | string): string {
  return CROP_META[crop as CropKey]?.icon ?? '🌱';
}

export function cropIconBg(crop: CropKey | string): string {
  return CROP_ICON_BG[crop as CropKey] ?? colors.selectedBg;
}
