// plantStageContent.ts
// Per-crop, per-planted-bucket copy shared by My Garden (3a) and Plant
// Detail (5a). Reworded from alertsEngine's STAGE_TABLE for these screens'
// tone; not imported from there since that table isn't exported and mixes
// in severity/alert-specific fields these screens don't use.
//
// STAGE_HEADLINE/NEXT_ACTION's 'w0' entries are unused dead data, same as
// alertsEngine's STAGE_TABLE — screens intercept bucket 'w0' themselves and
// call plantingGuidanceFor() (engines/plantingGuide.ts) instead, since
// "not planted yet" needs real when/how-to-plant guidance, not the
// established-plant care tips these tables hold for every other bucket.

import { CropKey } from './engines/scheduleEngine';
import { PlantedBucket } from './engines/alertsEngine';

export const BUCKET_LABEL: Record<PlantedBucket, string> = {
  w0: 'not planted yet',
  w2: '1–4 wks ago',
  w4: '4–8 wks ago',
  w8: '8+ wks ago',
};

export const STAGE_HEADLINE: Partial<Record<CropKey, Record<PlantedBucket, string>>> = {
  tomatoes: {
    w0: 'Establishing roots',
    w2: 'Vegetative growth',
    w4: 'Flowering & fruit set',
    w8: 'Fruiting & ripening',
  },
  cucumbers: {
    w0: 'Establishing',
    w2: 'Vining & flowering',
    w4: 'Fruiting',
    w8: 'Peak production',
  },
  lettuce: {
    w0: 'Seedling stage',
    w2: 'Leafing out',
    w4: 'Near harvest size',
    w8: 'Mature, bolt risk rising',
  },
  carrots: {
    w0: 'Germinating',
    w2: 'Root development starting',
    w4: 'Root development',
    w8: 'Nearing maturity',
  },
  peppers: {
    w0: 'Establishing',
    w2: 'Vegetative growth',
    w4: 'Flowering & fruit set',
    w8: 'Fruiting, coloring up',
  },
  basil: {
    w0: 'Germinating',
    w2: 'Leafing out',
    w4: 'Ready to harvest',
    w8: 'Mature, bolt risk rising',
  },
  potatoes: {
    w0: 'Sprouting',
    w2: 'Vegetative growth',
    w4: 'Flowering, tubers bulking',
    w8: 'Bulking, nearing maturity',
  },
  garlic: {
    w0: 'Establishing',
    w2: 'Leafing out',
    w4: 'Bulbing',
    w8: 'Curing soon',
  },
  strawberries: {
    w0: 'Establishing',
    w2: 'Runners & leaves',
    w4: 'Flowering',
    w8: 'Fruiting',
  },
  squash: {
    w0: 'Establishing',
    w2: 'Vining',
    w4: 'Flowering',
    w8: 'Fruiting',
  },
  corn: {
    w0: 'Germinating',
    w2: 'Vegetative growth',
    w4: 'Tasseling',
    w8: 'Filling ears',
  },
  onions: {
    w0: 'Establishing',
    w2: 'Leafing out',
    w4: 'Bulbing',
    w8: 'Curing soon',
  },
  broccoli: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Head forming', w8: 'Nearing harvest' },
  cauliflower: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Head forming', w8: 'Nearing harvest' },
  cabbage: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Head forming', w8: 'Nearing harvest' },
  kale: { w0: 'Seedling stage', w2: 'Leafing out', w4: 'Established, harvestable', w8: 'Full production' },
  spinach: { w0: 'Seedling stage', w2: 'Leafing out', w4: 'Near harvest size', w8: 'Mature, bolt risk rising' },
  chard: { w0: 'Seedling stage', w2: 'Leafing out', w4: 'Established, harvestable', w8: 'Full production' },
  beets: { w0: 'Germinating', w2: 'Root development starting', w4: 'Root development', w8: 'Nearing maturity' },
  radishes: { w0: 'Germinating', w2: 'Root development starting', w4: 'Root development', w8: 'Ready soon' },
  turnips: { w0: 'Germinating', w2: 'Root development starting', w4: 'Root development', w8: 'Nearing maturity' },
  peas: { w0: 'Germinating', w2: 'Vining', w4: 'Flowering, pods setting', w8: 'Podding' },
  beans: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Flowering, pods setting', w8: 'Podding' },
  zucchini: { w0: 'Establishing', w2: 'Vining', w4: 'Flowering', w8: 'Fruiting' },
  pumpkin: { w0: 'Establishing', w2: 'Vining', w4: 'Flowering', w8: 'Fruiting, sizing up' },
  eggplant: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Flowering & fruit set', w8: 'Fruiting' },
  celery: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Stalk development', w8: 'Nearing maturity' },
  asparagus: { w0: 'Establishing', w2: 'Fern growth', w4: 'Building root reserves', w8: 'End of establishment year' },
  brusselssprouts: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Sprouts forming', w8: 'Filling out' },
  leeks: { w0: 'Establishing', w2: 'Leafing out', w4: 'Shaft thickening', w8: 'Nearing harvest' },
  okra: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Flowering', w8: 'Podding' },
  sweetpotatoes: { w0: 'Establishing', w2: 'Vining', w4: 'Root development', w8: 'Bulking, nearing maturity' },
  rutabaga: { w0: 'Germinating', w2: 'Root development starting', w4: 'Root development', w8: 'Nearing maturity' },
  kohlrabi: { w0: 'Germinating', w2: 'Bulb forming', w4: 'Bulb sizing up', w8: 'Nearing maturity' },
  arugula: { w0: 'Seedling stage', w2: 'Leafing out', w4: 'Near harvest size', w8: 'Mature, bolt risk rising' },
  collards: { w0: 'Seedling stage', w2: 'Leafing out', w4: 'Established, harvestable', w8: 'Full production' },
  bokchoy: { w0: 'Seedling stage', w2: 'Leafing out', w4: 'Near harvest size', w8: 'Mature, bolt risk rising' },
  cilantro: { w0: 'Germinating', w2: 'Leafing out', w4: 'Near harvest size', w8: 'Bolt risk rising' },
  parsley: { w0: 'Germinating', w2: 'Leafing out', w4: 'Established, harvestable', w8: 'Full production' },
  mint: { w0: 'Establishing', w2: 'Spreading', w4: 'Established, harvestable', w8: 'Full production' },
  rosemary: { w0: 'Establishing', w2: 'Rooting in', w4: 'Established, light harvest', w8: 'Full flavor' },
  thyme: { w0: 'Establishing', w2: 'Rooting in', w4: 'Established, light harvest', w8: 'Full flavor' },
  oregano: { w0: 'Establishing', w2: 'Rooting in', w4: 'Established, light harvest', w8: 'Full flavor' },
  dill: { w0: 'Germinating', w2: 'Leafing out', w4: 'Near harvest size', w8: 'Bolt risk rising' },
  chives: { w0: 'Establishing', w2: 'Leafing out', w4: 'Established, harvestable', w8: 'Full production' },
  sage: { w0: 'Establishing', w2: 'Rooting in', w4: 'Established, light harvest', w8: 'Full flavor' },
  watermelon: { w0: 'Establishing', w2: 'Vining', w4: 'Flowering', w8: 'Fruiting, sizing up' },
  cantaloupe: { w0: 'Establishing', w2: 'Vining', w4: 'Flowering', w8: 'Fruiting, ripening' },
  blueberries: { w0: 'Establishing', w2: 'Rooting in', w4: 'Leafing out', w8: 'End of establishment year' },
  raspberries: { w0: 'Establishing', w2: 'Cane growth', w4: 'Cane growth continuing', w8: 'End of establishment year' },
  blackberries: { w0: 'Establishing', w2: 'Cane growth', w4: 'Cane growth continuing', w8: 'End of establishment year' },
  grapes: { w0: 'Establishing', w2: 'Vine growth', w4: 'Establishing root system', w8: 'End of establishment year' },
  rhubarb: { w0: 'Establishing', w2: 'Leafing out', w4: 'Building root reserves', w8: 'End of establishment year' },
  figs: { w0: 'Establishing', w2: 'Leafing out', w4: 'Building root reserves', w8: 'End of establishment year' },
  marigold: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Budding up', w8: 'Full bloom' },
  zinnia: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Budding up', w8: 'Full bloom' },
  sunflower: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Budding up', w8: 'Full bloom' },
  cosmos: { w0: 'Establishing', w2: 'Vegetative growth', w4: 'Budding up', w8: 'Full bloom' },
  nasturtium: { w0: 'Establishing', w2: 'Vining growth', w4: 'Budding up', w8: 'Full bloom' },
  pansy: { w0: 'Establishing', w2: 'Leafing out', w4: 'Budding up', w8: 'Full bloom' },
};

export const NEXT_ACTION: Partial<Record<CropKey, Record<PlantedBucket, string>>> = {
  tomatoes: {
    w0: 'Keep soil evenly moist and hold off on heavy feeding until new growth kicks in.',
    w2: 'Consistent watering now sets up healthier fruiting later.',
    w4: 'Switch to a 5-10-10 feed; if it is an indeterminate variety, pinch the shoots in each stem-branch V.',
    w8: 'Keep watering steady. Big swings in soil moisture now can crack ripening fruit.',
  },
  cucumbers: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Keep watering even. Inconsistent watering around flowering can make fruit bitter.',
    w4: 'Check daily. Cucumbers hide under leaves and go from ready to overripe fast.',
    w8: 'Pick slicers at 6–8" every day or two so the vine keeps setting.',
  },
  lettuce: {
    w0: 'Keep consistently moist and thin crowded seedlings for airflow.',
    w2: 'Keep an eye on moisture. Shallow roots dry out fast.',
    w4: 'Start checking daily, especially once warmer weather arrives.',
    w8: 'Harvest soon. Older lettuce bolts fast once heat arrives.',
  },
  carrots: {
    w0: 'Keep the soil surface consistently moist until you see sprouts.',
    w2: 'Consistent watering now helps avoid forked or split roots later.',
    w4: 'Keep watering even. This is when root shape is being set.',
    w8: 'Watch for shoulders showing at the soil surface as a sign they are close to ready.',
  },
  peppers: {
    w0: 'Keep soil evenly moist. Avoid overwatering young seedlings.',
    w2: 'Steady watering supports the first flowers about to appear.',
    w4: 'Keep watering consistent. Uneven moisture during fruit set causes blossom drop.',
    w8: 'Leave peppers on the plant to color up fully for the sweetest flavor.',
  },
  basil: {
    w0: 'Keep soil warm and consistently moist while it germinates.',
    w2: 'Pinch the growing tips to encourage bushier growth.',
    w4: 'Snip from the top regularly. That keeps it productive and delays flowering.',
    w8: 'Pinch off flower spikes right away or the leaves turn bitter.',
  },
  potatoes: {
    w0: 'Keep soil moist and hill soil around stems as they emerge.',
    w2: 'Keep hilling as plants grow to protect developing tubers from light.',
    w4: 'Keep watering consistent. Tubers are bulking up now.',
    w8: 'Ease off watering as foliage yellows. That is the harvest signal.',
  },
  garlic: {
    w0: 'Keep soil moist while roots establish.',
    w2: 'Steady moisture now supports bulb development later.',
    w4: 'Water needs increase as bulbs start to size up.',
    w8: 'Reduce watering as leaves yellow. Harvest once 5–6 leaves have browned.',
  },
  strawberries: {
    w0: 'Keep crowns moist but not waterlogged.',
    w2: 'Remove early runners so the plant focuses energy on itself.',
    w4: 'Keep watering consistent. This sets fruit size.',
    w8: 'Pick every couple of days once berries redden. Shallow roots dry out fast.',
  },
  squash: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Plants sprawl quickly now. Keep watering consistent to support rapid growth.',
    w4: 'Watch for both male and female flowers. Bees need to be around for fruit to set.',
    w8: 'Harvest summer squash small and often to keep the plant producing.',
  },
  corn: {
    w0: 'Keep soil moist until seedlings are up.',
    w2: 'Steady watering builds a strong stalk.',
    w4: 'Do not let it dry out now. This is the most water-critical stage.',
    w8: 'Check for milky kernels and brown, dry silks as the harvest signal.',
  },
  onions: {
    w0: 'Keep soil consistently moist near the surface. Shallow roots dry out fast.',
    w2: 'Steady watering builds the leaf growth that determines bulb size.',
    w4: 'Keep water needs high. Bulbs are swelling now.',
    w8: 'Stop watering once tops yellow and fall over. That is the cue bulbs are ready.',
  },
  broccoli: {
    w0: 'Keep soil evenly moist while roots establish.',
    w2: 'Consistent watering now builds the leaf growth the head will draw on.',
    w4: 'Do not let it dry out. Water stress now causes small or loose heads.',
    w8: 'Harvest the center head while buds are still tight, before any yellow shows.',
  },
  cauliflower: {
    w0: 'Keep soil evenly moist while roots establish.',
    w2: 'Consistent watering supports steady, unchecked growth.',
    w4: 'Keep watering even. Any check in growth causes small or bitter heads.',
    w8: 'Once the head is visible, tie outer leaves over it to keep it white.',
  },
  cabbage: {
    w0: 'Keep soil evenly moist while roots establish.',
    w2: 'Consistent watering now builds the leaf growth the head will draw on.',
    w4: 'Keep watering steady. Splits happen when dry spells are followed by heavy watering.',
    w8: 'Heads are ready once firm to a gentle squeeze.',
  },
  kale: {
    w0: 'Keep soil consistently moist while seedlings establish.',
    w2: 'Thin crowded seedlings so remaining plants have room to fill out.',
    w4: 'Harvest outer leaves as needed. New growth keeps coming from the center.',
    w8: 'Keep picking outer leaves regularly. Flavor sweetens after a light frost.',
  },
  spinach: {
    w0: 'Keep soil consistently moist until you see sprouts.',
    w2: 'Thin crowded seedlings for airflow and room to size up.',
    w4: 'Start checking daily once warmer weather arrives; it bolts fast.',
    w8: 'Harvest soon. Older spinach turns bitter and bolts once heat sets in.',
  },
  chard: {
    w0: 'Keep soil consistently moist while seedlings establish.',
    w2: 'Thin crowded seedlings so remaining plants have room to fill out.',
    w4: 'Harvest outer leaves as needed. New growth keeps coming from the center.',
    w8: 'Keep picking outer leaves regularly. It keeps producing all season.',
  },
  beets: {
    w0: 'Keep the soil surface consistently moist until you see sprouts.',
    w2: 'Thin seedlings to a few inches apart so roots have room to size up.',
    w4: 'Keep watering even. This is when root shape is being set.',
    w8: 'Roots are usually ready once shoulders show at the soil surface.',
  },
  radishes: {
    w0: 'Keep the soil surface consistently moist until you see sprouts.',
    w2: 'Thin seedlings so roots have room; crowding causes small, misshapen radishes.',
    w4: 'Keep watering even. Irregular watering causes cracked or woody roots.',
    w8: 'Pull them promptly once sized up. They turn hot and pithy if left too long.',
  },
  turnips: {
    w0: 'Keep the soil surface consistently moist until you see sprouts.',
    w2: 'Thin seedlings so roots have room to size up.',
    w4: 'Keep watering even. This is when root shape is being set.',
    w8: 'Pull once golf-ball to tennis-ball sized; larger roots turn woody.',
  },
  peas: {
    w0: 'Keep the soil surface consistently moist until you see sprouts.',
    w2: 'Give vines something to climb. Consistent watering supports steady growth.',
    w4: 'Keep watering even as flowers appear; dry spells now reduce pod set.',
    w8: 'Pick every day or two once pods fill out. Regular picking keeps more coming.',
  },
  beans: {
    w0: 'Keep soil evenly moist. Seeds can rot in waterlogged soil.',
    w2: 'Consistent watering now supports strong vegetative growth before flowering.',
    w4: 'Keep watering steady as flowers appear; dry spells now reduce pod set.',
    w8: 'Pick regularly once pods fill out. Beans left too long turn tough and stringy.',
  },
  zucchini: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Plants sprawl quickly now. Keep watering consistent to support rapid growth.',
    w4: 'Watch for both male and female flowers. Bees need to be around for fruit to set.',
    w8: 'Check daily once it starts. Size doubles fast and oversized ones turn tough.',
  },
  pumpkin: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Plants sprawl quickly now. Give vines plenty of room.',
    w4: 'Watch for both male and female flowers. Bees need to be around for fruit to set.',
    w8: 'Let fruit fully color and the vine start to die back before harvesting.',
  },
  eggplant: {
    w0: 'Keep soil evenly moist. Avoid overwatering young seedlings.',
    w2: 'Steady watering supports the first flowers about to appear.',
    w4: 'Keep watering consistent. Uneven moisture during fruit set causes drop.',
    w8: 'Harvest while skin is still glossy; dull skin means it is overripe.',
  },
  celery: {
    w0: 'Keep soil evenly moist while roots establish; celery does not tolerate drying out.',
    w2: 'Water frequently. Celery is thirsty throughout its whole season.',
    w4: 'Do not let it dry out even briefly. Stress now causes stringy, bitter stalks.',
    w8: 'Harvest outer stalks as needed, or cut the whole head at the base.',
  },
  asparagus: {
    w0: 'Keep crowns moist while roots establish. Do not harvest this first year.',
    w2: 'Let the ferny top growth run. It is building the root system for future years.',
    w4: 'Keep watering steady. Strong fern growth now means a better harvest in year three.',
    w8: 'Leave the ferns standing through fall; they feed the roots for next spring.',
  },
  brusselssprouts: {
    w0: 'Keep soil evenly moist while roots establish.',
    w2: 'Consistent watering now builds the leaf growth sprouts will draw on.',
    w4: 'Keep watering steady as sprouts begin forming along the stalk.',
    w8: 'Harvest from the bottom up as sprouts firm up; flavor improves after a light frost.',
  },
  leeks: {
    w0: 'Keep soil consistently moist while roots establish.',
    w2: 'Steady watering supports the leaf growth that feeds the shaft.',
    w4: 'Hill soil up around the stem as it grows to blanch it white.',
    w8: 'Harvest once the shaft is an inch or more thick, any time you need them.',
  },
  okra: {
    w0: 'Keep soil moist until seedlings are up; okra likes it warm.',
    w2: 'Consistent watering now supports strong vegetative growth before flowering.',
    w4: 'Keep watering steady as flowers appear.',
    w8: 'Pick pods every day or two while young and tender; overgrown pods turn woody.',
  },
  sweetpotatoes: {
    w0: 'Keep soil consistently moist while slips establish.',
    w2: 'Vines will start to sprawl. Consistent watering supports root development below.',
    w4: 'Keep watering steady. This is when the roots are bulking up.',
    w8: 'Ease off watering as the season winds down; that helps roots cure for storage.',
  },
  rutabaga: {
    w0: 'Keep the soil surface consistently moist until you see sprouts.',
    w2: 'Thin seedlings so roots have room to size up.',
    w4: 'Keep watering even. This is when root shape is being set.',
    w8: 'Roots hold well in the ground; harvest once they reach a good size.',
  },
  kohlrabi: {
    w0: 'Keep soil consistently moist while seedlings establish.',
    w2: 'Consistent watering now supports the bulb starting to swell above the soil.',
    w4: 'Keep watering even as the bulb sizes up.',
    w8: 'Harvest while the bulb is still small and tender; oversized ones turn woody.',
  },
  arugula: {
    w0: 'Keep soil consistently moist until you see sprouts.',
    w2: 'Thin crowded seedlings for airflow and room to fill out.',
    w4: 'Start checking daily once warmer weather arrives; it bolts fast.',
    w8: 'Harvest soon. It turns sharp and peppery once it starts to bolt.',
  },
  collards: {
    w0: 'Keep soil consistently moist while seedlings establish.',
    w2: 'Thin crowded seedlings so remaining plants have room to fill out.',
    w4: 'Harvest outer leaves as needed. New growth keeps coming from the center.',
    w8: 'Keep picking outer leaves regularly. Flavor sweetens after a light frost.',
  },
  bokchoy: {
    w0: 'Keep soil consistently moist until you see sprouts.',
    w2: 'Thin crowded seedlings for airflow and room to fill out.',
    w4: 'Start checking daily once warmer weather arrives; it bolts fast.',
    w8: 'Harvest soon. It turns bitter fast once it starts to bolt.',
  },
  cilantro: {
    w0: 'Keep soil consistently moist until you see sprouts.',
    w2: 'Thin crowded seedlings for airflow.',
    w4: 'Start checking daily once warmer weather arrives; it bolts fast in heat.',
    w8: 'Harvest soon. Once it bolts, leaves turn bitter, save the flowers for coriander seed.',
  },
  parsley: {
    w0: 'Keep soil consistently moist; parsley is slow and can take weeks to sprout.',
    w2: 'Thin crowded seedlings for airflow.',
    w4: 'Snip outer stems as needed. New growth keeps coming from the center.',
    w8: 'Keep harvesting outer stems regularly to encourage fresh growth.',
  },
  mint: {
    w0: 'Keep soil consistently moist while it establishes.',
    w2: 'It spreads fast. Keep it contained if you do not want it taking over the bed.',
    w4: 'Snip from the top regularly. That keeps it bushy and productive.',
    w8: 'Keep harvesting regularly. Frequent picking is what keeps it productive.',
  },
  rosemary: {
    w0: 'Keep soil lightly moist while roots establish, then ease off.',
    w2: 'Let the soil surface dry between waterings. It dislikes wet roots.',
    w4: 'Water sparingly. Rosemary is drought-tolerant once established.',
    w8: 'Snip sprigs as needed; regular light harvesting encourages bushier growth.',
  },
  thyme: {
    w0: 'Keep soil lightly moist while roots establish, then ease off.',
    w2: 'Let the soil surface dry between waterings. It dislikes wet roots.',
    w4: 'Water sparingly. Thyme is drought-tolerant once established.',
    w8: 'Snip sprigs as needed; regular light harvesting encourages bushier growth.',
  },
  oregano: {
    w0: 'Keep soil lightly moist while roots establish, then ease off.',
    w2: 'Let the soil surface dry between waterings. It dislikes wet roots.',
    w4: 'Water sparingly; it is more flavorful when grown a little lean.',
    w8: 'Snip sprigs as needed; regular light harvesting encourages bushier growth.',
  },
  dill: {
    w0: 'Keep soil consistently moist until you see sprouts.',
    w2: 'Thin crowded seedlings for airflow.',
    w4: 'Start checking daily once warmer weather arrives; it bolts fast in heat.',
    w8: 'Harvest soon. Once it flowers, leaves turn sparse, save the heads for seed.',
  },
  chives: {
    w0: 'Keep soil consistently moist while seedlings establish.',
    w2: 'Thin crowded seedlings for airflow.',
    w4: 'Snip from the outside as needed. New growth keeps coming from the center.',
    w8: 'Keep harvesting regularly; frequent picking encourages fresh, tender growth.',
  },
  sage: {
    w0: 'Keep soil lightly moist while roots establish, then ease off.',
    w2: 'Let the soil surface dry between waterings. It dislikes wet roots.',
    w4: 'Water sparingly. Sage is drought-tolerant once established.',
    w8: 'Snip leaves as needed; avoid heavy harvesting until the plant is well established.',
  },
  watermelon: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Plants sprawl quickly now. Give vines plenty of room.',
    w4: 'Watch for flowers. Bees need to be around for fruit to set.',
    w8: 'Check the tendril nearest the fruit; it browning and drying is a ripeness cue.',
  },
  cantaloupe: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Plants sprawl quickly now. Give vines plenty of room.',
    w4: 'Watch for flowers. Bees need to be around for fruit to set.',
    w8: 'A ripe melon slips easily from the vine with gentle pressure.',
  },
  blueberries: {
    w0: 'Keep soil consistently moist; blueberries have shallow roots and need acidic soil.',
    w2: 'Water regularly while it roots in. Mulch helps hold moisture.',
    w4: 'Keep watering steady. This first year is about building a strong root system.',
    w8: 'Expect only a light harvest, if any, this first year. Fuller crops come in future years.',
  },
  raspberries: {
    w0: 'Keep soil consistently moist while canes root in.',
    w2: 'New cane growth is establishing. Keep watering steady.',
    w4: 'Keep watering consistent as canes continue to develop.',
    w8: 'This first season is mostly about establishing; fuller harvests come next year.',
  },
  blackberries: {
    w0: 'Keep soil consistently moist while canes root in.',
    w2: 'New cane growth is establishing. Keep watering steady.',
    w4: 'Keep watering consistent as canes continue to develop.',
    w8: 'This first season is mostly about establishing; fuller harvests come next year.',
  },
  grapes: {
    w0: 'Keep soil consistently moist while roots establish.',
    w2: 'Train the young vine onto its trellis or support as it grows.',
    w4: 'This first year is about building roots and a strong trunk, not fruit.',
    w8: 'Expect little to no fruit this first year; full production typically starts around year three.',
  },
  rhubarb: {
    w0: 'Keep soil consistently moist while roots establish. Do not harvest this first year.',
    w2: 'Let the plant grow undisturbed. It is building the root system for future years.',
    w4: 'Keep watering steady. A strong first year means a better harvest starting next year.',
    w8: 'Leave the plant alone through fall; it is storing energy in the roots for next spring.',
  },
  figs: {
    w0: 'Keep soil consistently moist while roots establish.',
    w2: 'Let the tree focus on establishing this first year rather than fruiting heavily.',
    w4: 'Keep watering steady while the root system develops.',
    w8: 'Expect only a light crop, if any, this first year. Fuller harvests come in future years.',
  },
  marigold: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Pinch growing tips once seedlings have a few sets of leaves to encourage bushier, fuller plants.',
    w4: 'First flower buds should be forming. Deadhead spent blooms regularly to keep new ones coming.',
    w8: 'Keep deadheading spent flowers. Regular deadheading is what keeps marigolds blooming until frost.',
  },
  zinnia: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Pinch the center stem once it has a few sets of leaves to encourage branching and more blooms.',
    w4: 'Buds are forming now. Keep watering consistent through this stage.',
    w8: 'Cut flowers regularly for bouquets; frequent cutting is what keeps zinnias blooming.',
  },
  sunflower: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Grows fast once established. Stake tall varieties in windy spots.',
    w4: 'The bud will start tracking the sun as it forms.',
    w8: "Leave the head on the stalk if you want to save seeds for birds or next year's planting.",
  },
  cosmos: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Pinch young plants to encourage bushier growth and more flowering stems.',
    w4: 'Feathery foliage fills in fast. Buds should start appearing soon.',
    w8: 'Deadhead regularly; cosmos blooms nonstop through frost if spent flowers are kept cut back.',
  },
  nasturtium: {
    w0: 'Keep soil consistently moist while roots take hold.',
    w2: 'Sprawls or vines quickly. Give it room, or a trellis for climbing types.',
    w4: 'Poor soil actually produces more flowers; hold off on feeding.',
    w8: 'Pick flowers and young leaves regularly for salads; that also keeps more blooms coming.',
  },
  pansy: {
    w0: 'Keep soil consistently moist while it establishes.',
    w2: 'Keep soil consistently moist while it establishes.',
    w4: 'Cool weather brings on the first flowers.',
    w8: 'Deadhead spent blooms regularly to keep new flowers coming.',
  },
};

export const NEXT_ACTION_ICON: Partial<Record<CropKey, string>> = {
  tomatoes: '✂️',
  cucumbers: '🧺',
  lettuce: '🌿',
  carrots: '🥕',
  peppers: '💧',
  basil: '✂️',
  potatoes: '⛏️',
  garlic: '🧄',
  strawberries: '🧺',
  squash: '🧺',
  corn: '🌽',
  onions: '🧅',
  broccoli: '🧺',
  cauliflower: '🧺',
  cabbage: '🧺',
  kale: '🌿',
  spinach: '🌿',
  chard: '🌿',
  beets: '🥕',
  radishes: '🥕',
  turnips: '🥕',
  peas: '🧺',
  beans: '🧺',
  zucchini: '🧺',
  pumpkin: '🧺',
  eggplant: '🧺',
  celery: '✂️',
  asparagus: '💧',
  brusselssprouts: '🧺',
  leeks: '⛏️',
  okra: '🧺',
  sweetpotatoes: '⛏️',
  rutabaga: '🥕',
  kohlrabi: '🥕',
  arugula: '🌿',
  collards: '🌿',
  bokchoy: '🌿',
  cilantro: '✂️',
  parsley: '✂️',
  mint: '✂️',
  rosemary: '✂️',
  thyme: '✂️',
  oregano: '✂️',
  dill: '✂️',
  chives: '✂️',
  sage: '✂️',
  watermelon: '🧺',
  cantaloupe: '🧺',
  blueberries: '💧',
  raspberries: '💧',
  blackberries: '💧',
  grapes: '💧',
  rhubarb: '💧',
  figs: '🧺',
  marigold: '✂️',
  zinnia: '✂️',
  sunflower: '💐',
  cosmos: '✂️',
  nasturtium: '🌿',
  pansy: '✂️',
};

// Rough sow/grow/harvest composition of a typical season, and its total
// length — used for the season bar and "~X wk season" / "~X weeks left"
// labels. Not tied to today's date; it's the shape of the season, not
// progress through it.
export const SEASON_SHAPE: Partial<
  Record<CropKey, { sow: number; grow: number; harvest: number; weeks: number }>
> = {
  tomatoes: { sow: 14, grow: 52, harvest: 34, weeks: 18 },
  cucumbers: { sow: 12, grow: 46, harvest: 30, weeks: 14 },
  lettuce: { sow: 20, grow: 45, harvest: 35, weeks: 8 },
  carrots: { sow: 25, grow: 50, harvest: 25, weeks: 11 },
  peppers: { sow: 15, grow: 50, harvest: 35, weeks: 18 },
  basil: { sow: 15, grow: 45, harvest: 40, weeks: 10 },
  potatoes: { sow: 20, grow: 55, harvest: 25, weeks: 15 },
  garlic: { sow: 10, grow: 60, harvest: 30, weeks: 20 },
  strawberries: { sow: 10, grow: 40, harvest: 50, weeks: 12 },
  squash: { sow: 12, grow: 45, harvest: 43, weeks: 13 },
  corn: { sow: 10, grow: 55, harvest: 35, weeks: 14 },
  onions: { sow: 15, grow: 55, harvest: 30, weeks: 16 },
  broccoli: { sow: 15, grow: 55, harvest: 30, weeks: 12 },
  cauliflower: { sow: 15, grow: 60, harvest: 25, weeks: 13 },
  cabbage: { sow: 15, grow: 60, harvest: 25, weeks: 13 },
  kale: { sow: 15, grow: 35, harvest: 50, weeks: 8 },
  spinach: { sow: 15, grow: 35, harvest: 50, weeks: 7 },
  chard: { sow: 15, grow: 35, harvest: 50, weeks: 9 },
  beets: { sow: 20, grow: 50, harvest: 30, weeks: 9 },
  radishes: { sow: 15, grow: 60, harvest: 25, weeks: 4 },
  turnips: { sow: 20, grow: 55, harvest: 25, weeks: 6 },
  peas: { sow: 15, grow: 50, harvest: 35, weeks: 9 },
  beans: { sow: 12, grow: 48, harvest: 40, weeks: 9 },
  zucchini: { sow: 12, grow: 43, harvest: 45, weeks: 9 },
  pumpkin: { sow: 12, grow: 53, harvest: 35, weeks: 16 },
  eggplant: { sow: 15, grow: 50, harvest: 35, weeks: 17 },
  celery: { sow: 20, grow: 55, harvest: 25, weeks: 17 },
  asparagus: { sow: 10, grow: 70, harvest: 20, weeks: 12 },
  brusselssprouts: { sow: 15, grow: 65, harvest: 20, weeks: 16 },
  leeks: { sow: 20, grow: 55, harvest: 25, weeks: 18 },
  okra: { sow: 12, grow: 48, harvest: 40, weeks: 14 },
  sweetpotatoes: { sow: 15, grow: 60, harvest: 25, weeks: 18 },
  rutabaga: { sow: 20, grow: 55, harvest: 25, weeks: 10 },
  kohlrabi: { sow: 15, grow: 55, harvest: 30, weeks: 7 },
  arugula: { sow: 15, grow: 30, harvest: 55, weeks: 5 },
  collards: { sow: 15, grow: 35, harvest: 50, weeks: 9 },
  bokchoy: { sow: 15, grow: 35, harvest: 50, weeks: 6 },
  cilantro: { sow: 15, grow: 35, harvest: 50, weeks: 6 },
  parsley: { sow: 20, grow: 35, harvest: 45, weeks: 10 },
  mint: { sow: 10, grow: 30, harvest: 60, weeks: 6 },
  rosemary: { sow: 10, grow: 40, harvest: 50, weeks: 10 },
  thyme: { sow: 10, grow: 40, harvest: 50, weeks: 9 },
  oregano: { sow: 10, grow: 40, harvest: 50, weeks: 8 },
  dill: { sow: 15, grow: 35, harvest: 50, weeks: 8 },
  chives: { sow: 15, grow: 35, harvest: 50, weeks: 8 },
  sage: { sow: 10, grow: 40, harvest: 50, weeks: 10 },
  watermelon: { sow: 12, grow: 53, harvest: 35, weeks: 16 },
  cantaloupe: { sow: 12, grow: 48, harvest: 40, weeks: 13 },
  blueberries: { sow: 10, grow: 60, harvest: 30, weeks: 14 },
  raspberries: { sow: 10, grow: 55, harvest: 35, weeks: 14 },
  blackberries: { sow: 10, grow: 55, harvest: 35, weeks: 14 },
  grapes: { sow: 10, grow: 65, harvest: 25, weeks: 16 },
  rhubarb: { sow: 10, grow: 70, harvest: 20, weeks: 14 },
  figs: { sow: 10, grow: 60, harvest: 30, weeks: 16 },
  marigold: { sow: 15, grow: 35, harvest: 50, weeks: 14 },
  zinnia: { sow: 12, grow: 33, harvest: 55, weeks: 12 },
  sunflower: { sow: 10, grow: 60, harvest: 30, weeks: 12 },
  cosmos: { sow: 12, grow: 33, harvest: 55, weeks: 11 },
  nasturtium: { sow: 12, grow: 38, harvest: 50, weeks: 10 },
  pansy: { sow: 15, grow: 35, harvest: 50, weeks: 10 },
};
